/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.hydrologis.libs.newage.swig;

public class doubleArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected doubleArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(doubleArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      snowJNI.delete_doubleArray(swigCPtr);
    }
    swigCPtr = 0;
  }

  public doubleArray(int nelements) {
    this(snowJNI.new_doubleArray(nelements), true);
  }

  public double getitem(int index) {
    return snowJNI.doubleArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, double value) {
    snowJNI.doubleArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_double cast() {
    long cPtr = snowJNI.doubleArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static doubleArray frompointer(SWIGTYPE_p_double t) {
    long cPtr = snowJNI.doubleArray_frompointer(SWIGTYPE_p_double.getCPtr(t));
    return (cPtr == 0) ? null : new doubleArray(cPtr, false);
  }

}
