/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.hydrologis.libs.newage.swig;

public class kriging {
  public static int initializepoint(double[] xbasin, double[] ybasin, double[] zbasin, int nbasin) {
    return krigingJNI.initializepoint(xbasin, ybasin, zbasin, nbasin);
  }

  public static int initializegrid(double[] window) {
    return krigingJNI.initializegrid(window);
  }

  public static int getValues(double[] xstation, double[] ystation, double[] zstation, int nstaz, double[] rain, double[] interpolatedrain) {
    return krigingJNI.getValues(xstation, ystation, zstation, nstaz, rain, interpolatedrain);
  }

  public static int finish() {
    return krigingJNI.finish();
  }

}
