/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.hydrologis.libs.newage.swig;

public class snow {
  public static void cstige_neve(SWIGTYPE_p_double params, SWIGTYPE_p_double area, SWIGTYPE_p_double z0, SWIGTYPE_p_double prec, SWIGTYPE_p_double tbac, SWIGTYPE_p_double hsnowprec, SWIGTYPE_p_double hsnow, SWIGTYPE_p_double peff) {
    snowJNI.cstige_neve(SWIGTYPE_p_double.getCPtr(params), SWIGTYPE_p_double.getCPtr(area), SWIGTYPE_p_double.getCPtr(z0), SWIGTYPE_p_double.getCPtr(prec), SWIGTYPE_p_double.getCPtr(tbac), SWIGTYPE_p_double.getCPtr(hsnowprec), SWIGTYPE_p_double.getCPtr(hsnow), SWIGTYPE_p_double.getCPtr(peff));
  }

}
