/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.hydrologis.libs.newage.swig;

public class temp {
  public static void cstige_temperature(SWIGTYPE_p_double params, SWIGTYPE_p_int nums, SWIGTYPE_p_double z0, SWIGTYPE_p_double quotasta, SWIGTYPE_p_double tsta, SWIGTYPE_p_double tbac) {
    tempJNI.cstige_temperature(SWIGTYPE_p_double.getCPtr(params), SWIGTYPE_p_int.getCPtr(nums), SWIGTYPE_p_double.getCPtr(z0), SWIGTYPE_p_double.getCPtr(quotasta), SWIGTYPE_p_double.getCPtr(tsta), SWIGTYPE_p_double.getCPtr(tbac));
  }

}
