package eu.hydrologis.jgrass.ui.actions;

import org.eclipse.jface.action.IAction;
import org.eclipse.jface.viewers.ISelection;
import org.eclipse.swt.graphics.Point;
import org.eclipse.ui.IWorkbenchWindow;
import org.eclipse.ui.IWorkbenchWindowActionDelegate;

import eu.hydrologis.jgrass.uibuilder.jgrassdependent.utils.UIBuilderActionSupporter;

/**
 * this class was generated by JGrass's createCommands script
 */
public class h_skyview extends UIBuilderActionSupporter implements
        IWorkbenchWindowActionDelegate {

    private IWorkbenchWindow window;

    public void dispose() {
    }

    public void init(IWorkbenchWindow window) {
        this.window = window;
    }

    public void run(IAction action) {
        isJGrass = true;
        isGrass = false;
        launchGui(window, new Point(450, 120));
    }

    public void selectionChanged(IAction action, ISelection selection) {
    }
}